name: Google App Script Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: namaggarwal/clasp-token-action@v0.0.1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
      - name: install dependencies
        run: |
          npm install
      - name: push to gas
        run: |
          npm run push
      - name: deploy new version
        run: |
          npm run build